### ISSUE TITLE
trimal.exe has stopped working message

### ISSUE THREAD

**Issue by kuhaudos** [inab/trimal#26]
Hi there,

I have been using trimal v.1.2 on a local computer using command prompt. When I tried to run a command line to trim my alignment this message "trimal.exe has stopped working message" popped up and the program stopped working. Can you please tell me what I have done wrong?
The command line was trimal -in <input file.phylip> -out <output file.phylip> -automated1

My guess was that the alignment file was too big. I'm trying to find if there's any size limitation for trimal but couldn't find any information on the main website. Could you please clarify this issue?

Thank you in advance

**Comment by scapella** [comment]
Hi there,

Would it be possible to use your alignment for testing trimAl.
So far I have used it with 5GB data alignment and trimAl has processed it.

My initial hypothesis are 1) it may be related to the Windows version which
is not under active development, and/or 2) related to the available RAM
memory at your computer since trimAl needs to load the alignment in memory
before process it.

Perhaps you can try with a smaller alignment to prove my second hypothesis.

Cheers,

S

On Fri, May 27, 2016 at 1:32 PM, kuhaudos <notifications@github.com> wrote:

> Hi there,
>
> I have been using trimal v.1.2 on a local computer using command prompt.
> When I tried to run a command line to trim my alignment this message
> "trimal.exe has stopped working message" popped up and the program stopped
> working. Can you please tell me what I have done wrong?
> The command line was trimal -in -out -automated1
>
> My guess was that the alignment file was too big. I'm trying to find if
> there's any size limitation for trimal but couldn't find any information on
> the main website. Could you please clarify this issue?
>
> Thank you in advance
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scapella/trimal/issues/26>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAH4h4J6n67UO_j5Uh_3LV1tlIK-g31kks5qFtZPgaJpZM4Ioas5>
> .
>



-- 
Salva
